language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3
otp_release:
  - 17.5
  - 18.3
sudo: false
before_script:
  - mix deps.get --only test
env:
  - MIX_ENV=test
script: mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
