language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
otp_release: '20.0'
sudo: false
before_script:
  - mix deps.get --only test
env:
  - MIX_ENV=test
script:
  - mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
jobs:
  include:
    - elixir: '1.10'
      otp_release: '21.0'
    - elixir: '1.11'
      otp_release: '21.0'
    - elixir: '1.11'
      otp_release: '23.0'
